# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: dev
spec:
  selector:
    app: kafka-broker
  ports:
    - port: 9092
      targetPort: 9092


---
#  Kafka Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  # Kafka Pod Details
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      hostname: kafka-broker
      containers:
        - name: kafka-broker
          image: confluentinc/cp-kafka:7.3.2
          imagePullPolicy: IfNotPresent
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: 10.96.2.1:2181
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-service:9092
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          ports:
            - containerPort: 9092
