apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 32000 # port that is exposed to the cluster
      targetPort: 27017 # port on which container is actually running
      nodePort: 32000
  type: NodePort
  