apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          args: [ "--dbpath","/data/db" ]

          # Authentication
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "admin"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
          imagePullPolicy: IfNotPresent

          # volume inside the container
          volumeMounts:
            - mountPath: /data/db
              name: mongo-volume-docker

      # Map the volume inside the container to emptyDir
#      volumes:
#        - name: mongo-volume-docker
#          emptyDir: { }
#      restartPolicy: Always


      # Map the Volume inside the container to Persistent_Volume and Persistent_Volume_Claim
      volumes:
        - name: mongo-volume-docker
          persistentVolumeClaim:
            claimName: mongo-pvc