DROP TABLE IF EXISTS TRANSACTIONS;

CREATE TABLE TRANSACTIONS(
	ID INT PRIMARY KEY,
	VALUE VARCHAR(20),
	STATUS VARCHAR(20),
	CREATED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	LAST_MODIFIED_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM TRANSACTIONS;
